version: '3.8'
services:
  nba-app:
    build:
      context: .
    ports:
      - "8000:8000"
      - "8501:8501"
    env_file:
      - .env_docker
    depends_on:
      - qdrant
    volumes:
      - ./nba_data/raw_parquet_files:/app/nba_data/raw_parquet_files
      - ./nba_data/processed_parquet_files:/app/nba_data/processed_parquet_files
      - ./logs:/app/logs

  qdrant: 
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_storage:/qdrant/storage
