version: '3.8'
services:
  nba-app:
    build:
      context: .
    ports:
      - "8000:8000"
      - "8501:8501"
    env_file:
      - .env
    depends_on:
      - qdrant
  # # The qdrant service runs in a separate Docker container and is connected to the nba-app service within the same network.
  qdrant: 
    image: qdrant/qdrant
    ports:
      - "6333:6333"
