version: '3.8'

services:
  nba-app:
    build:
      context: .
    command: uvicorn backend.run_backend_server_main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"  # FastAPI
    env_file:
      - .env_docker
    depends_on:
      - qdrant
    networks:
      - nba-network
    volumes:
      - ./nba_data/raw_parquet_files:/app/nba_data/raw_parquet_files
      - ./nba_data/processed_parquet_files:/app/nba_data/processed_parquet_files
      - ./nba_data/recent_searches:/app/nba_data/recent_searches
      - ./logs:/app/logs

  nginx:
    image: nginx:alpine
    ports:
      - "8501:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - streamlit-app
    networks:
      - nba-network

  streamlit-app:
    build:
      context: .
    command: streamlit run streamlit_frontend/src/app.py --server.port=8501 --server.address=0.0.0.0 --server.headless true
    expose:
      - "8501"
    env_file:
      - .env_docker
    depends_on:
      - nba-app
    networks:
      - nba-network
    environment:
      FAST_API_HOST: nba-app
    volumes:
      - ./logs:/app/logs

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"  # Qdrant
    networks:
      - nba-network
    volumes:
      - ./qdrant_storage:/qdrant/storage

networks:
  nba-network:
    driver: bridge
